### ISSUE TITLE
Submiting form redirects to landing page of the website

### ISSUE THREAD

**Issue by MouiseLichel** [mnakalay/Concrete5-Super-User-recovery#1]
Hello,
I needed to reset my password and found your script, but was not abble to make it work. When I submitted the new password form I was redirected to the homepage of my website.
I had to change a bit the script to make it work :
I replaced `<form` method="post" `action="/">` line 533
by `<form` method="post" `action="/?p=mypassword">`

Btw I am using Concrete 8.5.4

**Comment by mnakalay** [comment]
@TheWardow thank you for letting me know I'll have a look.

Glad the script could help.

**Comment by mnakalay** [comment]
This is now fixed. I forgot to rename a parameter and that was creating the issue.
Closing.
